package com.salon.community.model;

public class Keys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KEYS.ID
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KEYS.KEY
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KEYS.STATUS
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KEYS.ID
     *
     * @return the value of KEYS.ID
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KEYS.ID
     *
     * @param id the value for KEYS.ID
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KEYS.KEY
     *
     * @return the value of KEYS.KEY
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KEYS.KEY
     *
     * @param key the value for KEYS.KEY
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KEYS.STATUS
     *
     * @return the value of KEYS.STATUS
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KEYS.STATUS
     *
     * @param status the value for KEYS.STATUS
     *
     * @mbg.generated Thu May 21 12:57:09 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}